// <auto-generated />
using Honkai_Star_Rail_Tier_List.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Honkai_Star_Rail_Tier_List.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311234858_CreateEidolons")]
    partial class CreateEidolons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TierAS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TierMOC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TierPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Eidolon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Level")
                        .IsUnique();

                    b.ToTable("Eidolons");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.SkillLevelValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillValues");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Eidolon", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithMany("Eidolons")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Skill", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.SkillLevelValue", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Skill", "Skill")
                        .WithMany("LevelValue")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Character", b =>
                {
                    b.Navigation("Eidolons");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Skill", b =>
                {
                    b.Navigation("LevelValue");
                });
#pragma warning restore 612, 618
        }
    }
}
