// <auto-generated />
using System;
using Honkai_Star_Rail_Tier_List.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Honkai_Star_Rail_Tier_List.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418003052_InitailCreate")]
    partial class InitailCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.BuildLightCone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LightConeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("LightConeId");

                    b.ToTable("BuildLightCones");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.BuildRelicSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelicSet1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelicSet2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("RelicSet1Id");

                    b.HasIndex("RelicSet2Id");

                    b.ToTable("BuildRelicSets");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.BuildStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Feet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstatPriority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildId")
                        .IsUnique();

                    b.ToTable("BuildStats");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TierAS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TierMOC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TierPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.CharacterGuide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterGuides");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.CharacterTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("TeamId");

                    b.ToTable("CharacterTeams");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Companion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Companions");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Eidolon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Level")
                        .IsUnique();

                    b.ToTable("Eidolons");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.LightCone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Obtain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LightCones");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.RelicSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FourPieceEffect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwoPieceEffect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RelicSets");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CompanionId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.SkillLevelValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillValues");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Strength", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterID");

                    b.ToTable("Strengths");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Weakness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterID");

                    b.ToTable("Weaknesss");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Build", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithMany("Builds")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.BuildLightCone", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Build", "Build")
                        .WithMany("LightCones")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.LightCone", "LightCone")
                        .WithMany()
                        .HasForeignKey("LightConeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("LightCone");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.BuildRelicSet", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Build", "Build")
                        .WithMany("RelicSets")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.RelicSet", "RelicSet1")
                        .WithMany()
                        .HasForeignKey("RelicSet1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.RelicSet", "RelicSet2")
                        .WithMany()
                        .HasForeignKey("RelicSet2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("RelicSet1");

                    b.Navigation("RelicSet2");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.BuildStats", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Build", "Build")
                        .WithOne("BuildStats")
                        .HasForeignKey("Honkai_Star_Rail_Tier_List.Models.BuildStats", "BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.CharacterGuide", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithOne("CharacterGuide")
                        .HasForeignKey("Honkai_Star_Rail_Tier_List.Models.CharacterGuide", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.CharacterTeam", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithMany("CharacterTeams")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Companion", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithMany("Companions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Eidolon", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithMany("Eidolons")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Skill", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId");

                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Companion", "Companion")
                        .WithMany("Skills")
                        .HasForeignKey("CompanionId");

                    b.Navigation("Character");

                    b.Navigation("Companion");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.SkillLevelValue", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Skill", "Skill")
                        .WithMany("LevelValue")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Strength", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithMany("Strengths")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.TeamMember", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Weakness", b =>
                {
                    b.HasOne("Honkai_Star_Rail_Tier_List.Models.Character", "Character")
                        .WithMany("Weaknesss")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Build", b =>
                {
                    b.Navigation("BuildStats")
                        .IsRequired();

                    b.Navigation("LightCones");

                    b.Navigation("RelicSets");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Character", b =>
                {
                    b.Navigation("Builds");

                    b.Navigation("CharacterGuide")
                        .IsRequired();

                    b.Navigation("CharacterTeams");

                    b.Navigation("Companions");

                    b.Navigation("Eidolons");

                    b.Navigation("Skills");

                    b.Navigation("Strengths");

                    b.Navigation("Weaknesss");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Companion", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Skill", b =>
                {
                    b.Navigation("LevelValue");
                });

            modelBuilder.Entity("Honkai_Star_Rail_Tier_List.Models.Team", b =>
                {
                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
